//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodMonkey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int id { get; set; }
        [Required]
        [MinLength(4)]
        public string name { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        [MinLength(4)]
        public string password { get; set; }
        public string type { get; set; }
        public int phone_number { get; set; }
        [Required]
        public string status { get; set; }
        public Nullable<int> NID_number { get; set; }
        public string area { get; set; }
        public string address { get; set; }
    }
}
