//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodMonkeyEntities : DbContext
    {
        public FoodMonkeyEntities()
            : base("name=FoodMonkeyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<announcement> announcements { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<report> reports { get; set; }
        public DbSet<site_info> site_info { get; set; }
        public DbSet<user> users { get; set; }
    }
}
