//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public int restaurant_id { get; set; }
        public string restaurant_name { get; set; }
        public int customer_id { get; set; }
        public int price_on_selling_time { get; set; }
        public int amount { get; set; }
        public string area { get; set; }
        public string address { get; set; }
    }
}
